<a href="https://colab.research.google.com/github/kulraj97/ML-Practise/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [5]:
dt=pd.read_csv("/content/drive/MyDrive/Mall_Customers.csv")


In [6]:
dt.sample(5)

CustomerID   Genre  Age  Annual_Income_(k$)  Spending_Score
108         109    Male   68                  63              43
97           98  Female   27                  60              50
168         169  Female   36                  87              27
23           24    Male   31                  25              73
131         132    Male   39                  71              75

In [9]:
x=dt.iloc[:,2:]
y=dt["Genre"]

In [10]:
x.shape,y.shape

((200, 3), (200,))

In [35]:
dt.Genre=[1 if each == "Male"  else 0 for each in dt.Genre]

In [36]:
import plotly.express as px

In [37]:
fig = px.scatter_3d(dt, x=dt['Age'], y=dt['Annual_Income_(k$)'], z=dt['Spending_Score'],
              color=dt['Genre'])
fig.show()

In [38]:
from sklearn.preprocessing import StandardScaler

In [39]:
sc=StandardScaler()

In [40]:
x=sc.fit_transform(x)

In [41]:
covariance_matrix=np.cov([dt["Age"],dt["Annual_Income_(k$)"],dt["Spending_Score"]])
covariance_matrix

array([[ 195.13316583,   -4.54874372, -118.04020101],
       [  -4.54874372,  689.83557789,    6.71658291],
       [-118.04020101,    6.71658291,  666.85427136]])

In [42]:
eigen_values,eigen_vectors=np.linalg.eig(covariance_matrix)

In [43]:
eigen_values

array([167.22852389, 700.26435482, 684.33013636])

In [44]:
eigen_vectors

array([[ 0.97320957,  0.1889742 , -0.1309652 ],
       [ 0.00551667, -0.58864102, -0.80837573],
       [ 0.22985365, -0.7859965 ,  0.57391358]])

In [45]:
pc = eigen_vectors[0:2]
pc

array([[ 0.97320957,  0.1889742 , -0.1309652 ],
       [ 0.00551667, -0.58864102, -0.80837573]])

In [46]:
transformed_dt = np.dot(dt.iloc[:,2:],pc.T)
transformed_dt

array([[  16.21795192,  -40.25145196],
       [  12.66383254,  -74.19219918],
       [  21.70198738,  -14.15817731],
       [  15.32308669,  -71.53630395],
       [  28.14344996,  -42.1709097 ],
       [  14.66981652,  -71.32208591],
       [  36.67807934,  -15.25270932],
       [  13.47462664,  -86.45597335],
       [  65.48302668,  -13.25623977],
       [  23.35730229,  -69.22173169],
       [  66.96203816,  -22.13182277],
       [  24.68728967,  -91.02029299],
       [  58.26116102,  -23.57848953],
       [  17.05219306,  -73.88535136],
       [  38.08569046,  -22.07758811],
       [  14.84384351,  -75.51313615],
       [  33.44701105,  -40.46152847],
       [  14.78894621,  -65.60392605],
       [  51.15531336,  -36.69477278],
       [  25.57415167,  -92.56648134],
       [  34.01393365,  -42.22745153],
       [  19.30516024,  -73.00089586],
       [  48.83716921,  -18.50413737],
       [  25.33339186,  -73.55643687],
       [  56.01108154,  -27.50130863],
       [  22.7752085 ,  -

In [49]:
new_dt=pd.DataFrame(transformed_dt,columns=["PC1","PC2"])
new_dt

PC1         PC2
0    16.217952  -40.251452
1    12.663833  -74.192199
2    21.701987  -14.158177
3    15.323087  -71.536304
4    28.143450  -42.170910
..         ...         ...
195  46.392988 -134.305521
196  63.938154  -96.555039
197  45.262030 -133.812039
198  54.674798  -95.018049
199  44.215641 -147.573505

[200 rows x 2 columns]

In [50]:
new_dt["Genre"]=dt["Genre"]

In [51]:
new_dt

PC1         PC2  Genre
0    16.217952  -40.251452      1
1    12.663833  -74.192199      1
2    21.701987  -14.158177      0
3    15.323087  -71.536304      0
4    28.143450  -42.170910      0
..         ...         ...    ...
195  46.392988 -134.305521      0
196  63.938154  -96.555039      0
197  45.262030 -133.812039      1
198  54.674798  -95.018049      1
199  44.215641 -147.573505      1

[200 rows x 3 columns]

In [52]:
fig=px.scatter(new_dt,x="PC1",y="PC2",color="Genre")
fig.show()